// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChon8ZmUSFPWmp4SfW-QnPjokBrsvjEno',
    appId: '1:267745445625:web:b7113a847ad15df1784428',
    messagingSenderId: '267745445625',
    projectId: 'zibene-47b89',
    authDomain: 'zibene-47b89.firebaseapp.com',
    storageBucket: 'zibene-47b89.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnbpSikIVMi4VXDyGI7q7IcM6EAPeij4k',
    appId: '1:267745445625:android:e332c67fa087dfd7784428',
    messagingSenderId: '267745445625',
    projectId: 'zibene-47b89',
    storageBucket: 'zibene-47b89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBneqL7T4xiU3QiO1VGVTeVWvG2eDPSRjs',
    appId: '1:267745445625:ios:ee13315c8b60b78a784428',
    messagingSenderId: '267745445625',
    projectId: 'zibene-47b89',
    storageBucket: 'zibene-47b89.firebasestorage.app',
    iosBundleId: 'com.example.zibeneSecurity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBneqL7T4xiU3QiO1VGVTeVWvG2eDPSRjs',
    appId: '1:267745445625:ios:ee13315c8b60b78a784428',
    messagingSenderId: '267745445625',
    projectId: 'zibene-47b89',
    storageBucket: 'zibene-47b89.firebasestorage.app',
    iosBundleId: 'com.example.zibeneSecurity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChon8ZmUSFPWmp4SfW-QnPjokBrsvjEno',
    appId: '1:267745445625:web:b69dbb5f09343af9784428',
    messagingSenderId: '267745445625',
    projectId: 'zibene-47b89',
    authDomain: 'zibene-47b89.firebaseapp.com',
    storageBucket: 'zibene-47b89.firebasestorage.app',
  );

}